
def reporteT(lista):
    f = open('Reportes/ReporteTokens.html', mode='w', encoding='UTF-8')
    f.write('<!DOCTYPE html>\n')
    f.write('<html lang="en">\n')
    f.write('   <head>\n')
    f.write('       <meta charset="UTF-8">\n')
    f.write('       <meta http-equiv="X-UA-Compatible" content="IE=edge">\n')
    f.write('       <meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
    f.write('       <link rel="stylesheet" type="text/css" href="styles.css"/>\n')
    f.write('       <title>TOKENS</title>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('       <div id="contenedor">\n')
    f.write('           <div id="encabezado">\n')
    f.write('               <div id="encabezado-logo"></div>\n')
    f.write('               <div id="encabezado-texto">\n')
    f.write('                   <h2>LFP Proyecto2<br>Reporte de Tokens</h2>\n')
    f.write('               </div>\n')
    f.write('           </div>\n')
    f.write('           <div id="cuerpo">\n')
    f.write('               <div id="tabla">\n')
    f.write('                   <table>\n')
    f.write('                       <thead>\n')
    f.write('                           <tr>\n')
    f.write('                               <th>#</th>\n')
    f.write('                               <th>Token</th>\n')
    f.write('                               <th>Lexema</th>\n')
    f.write('                               <th>Fila</th>\n')
    f.write('                               <th>Columna</th>\n')
    f.write('                           </tr>\n')
    f.write('                       </thead>\n')
    f.write('                       <tbody>\n')
    for i in range(len(lista)):
        f.write('                           <tr>\n')
        f.write('                               <th>'+ str(i+1)+ '</th>\n')
        f.write('                               <td>' + lista[i][1] +'</td>\n')
        f.write('                               <td>' + lista[i][0] + '</td>\n')
        f.write('                               <td>' + lista[i][2] + '</td>\n')
        f.write('                               <td>' + lista[i][3] + '</td>\n')
        f.write('                           </tr>\n')
    f.write('                       </tbody>\n')
    f.write('                   </table>\n')
    f.write('               </div>\n')
    f.write('           </div>\n')
    f.write('       </div>\n')
    f.write('   </body>\n')
    f.write('</html>\n')
    f.close()

def reporteE(lista):
    f = open('Reportes/ReporteErrores.html', mode='w', encoding='UTF-8')
    f.write('<!DOCTYPE html>\n')
    f.write('<html lang="en">\n')
    f.write('   <head>\n')
    f.write('       <meta charset="UTF-8">\n')
    f.write('       <meta http-equiv="X-UA-Compatible" content="IE=edge">\n')
    f.write('       <meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
    f.write('       <link rel="stylesheet" type="text/css" href="styles.css"/>\n')
    f.write('       <title>ERRORES</title>\n')
    f.write('   </head>\n')
    f.write('   <body>\n')
    f.write('       <div id="contenedor">\n')
    f.write('           <div id="encabezado">\n')
    f.write('               <div id="encabezado-logo"></div>\n')
    f.write('               <div id="encabezado-texto">\n')
    f.write('                   <h2>LFP Proyecto2<br>Reporte de Errores</h2>\n')
    f.write('               </div>\n')
    f.write('           </div>\n')
    f.write('           <div id="cuerpo">\n')
    f.write('               <div id="tabla">\n')
    f.write('                   <table>\n')
    f.write('                       <thead>\n')
    f.write('                           <tr>\n')
    f.write('                               <th>#</th>\n')
    f.write('                               <th>Error</th>\n')
    f.write('                               <th>Mensaje</th>\n')
    f.write('                               <th>Tipo</th>\n')
    f.write('                               <th>Fila</th>\n')
    f.write('                               <th>Columna</th>\n')
    f.write('                           </tr>\n')
    f.write('                       </thead>\n')
    f.write('                       <tbody>\n')
    for i in range(len(lista)):
        f.write('                           <tr>\n')
        f.write('                               <th>'+ str(i+1)+ '</th>\n')
        f.write('                               <td>' + lista[i][0] +'</td>\n')
        f.write('                               <td>' + lista[i][1] + '</td>\n')
        f.write('                               <td>' + lista[i][2] + '</td>\n')
        f.write('                               <td>' + str(lista[i][3]) + '</td>\n')
        f.write('                               <td>' + str(lista[i][4]) + '</td>\n')
        f.write('                           </tr>\n')
    f.write('                       </tbody>\n')
    f.write('                   </table>\n')
    f.write('               </div>\n')
    f.write('           </div>\n')
    f.write('       </div>\n')
    f.write('   </body>\n')
    f.write('</html>\n')
    f.close()